# 声明版本
version: "3"
# 定义服务
services:
  # 服务名称，能够在同一个网络内按照名称访问
  consul:
    # 指定镜像
    image: cap1573/consul
    # 镜像对外映射的端口
    ports:
      - "8500:8500"
  jaeger:
    image: cap1573/jaeger
    ports:
      - "6831:6831"
      - "16686:16686"
  hystrix-dashboard:
    image: cap1573/hystrix-dashboard
    ports:
      - "9002:9002"
  prometheus:
    image: cap1573/prometheus
    # 把外部yml文件挂载到容器中
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  # 监控看板
  grafana:
    image: cap1573/grafana
    ports:
      - "3000:3000"