# 全局配置
global:
  # 默认值，每15秒采集一次
  scrape_interval: 15s
  external_labels:
    monitor: 'go-micro-monitor'
scrape_configs:
  # 监控的服务
  - job_name: 'order'
    # 覆盖上述默认值，5秒采集一次
    scrape_interval: 5s
    static_configs:
      # 被监控服务的地址
      - targets: ["172.25.69.11:9092"]